name: Sync with Google Calendar

on:
  workflow_dispatch:
  schedule:
    # This triggers the workflow every day at 4:00 UTC
    - cron: "30 4 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install poetry
        run: |
          export POETRY_HOME=/opt/poetry
          curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0
          export PATH="/opt/poetry/bin:$PATH"
          echo "/opt/poetry/bin" >> $GITHUB_PATH
          poetry --version

      - name: Install deps
        run: poetry install

      - name: Prepare service-account.json
        env:
          SERVICE_ACCOUNT_KEY_CONTENTS: ${{ secrets.SERVICE_ACCOUNT_KEY_CONTENTS }}
        run: |
          mkdir .creds
          touch .creds/service-account.json
          echo "$SERVICE_ACCOUNT_KEY_CONTENTS" > .creds/service-account.json

      - name: Sync
        env:
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          SCHEDULE_PAGE_URL: ${{ secrets.SCHEDULE_PAGE_URL }}
          UNIVERSITY_LOCATION: ${{ secrets.UNIVERSITY_LOCATION }}
        run: poetry run python3 main.py

      - uses: gautamkrishnar/keepalive-workflow@v1
