name: Sync with Google Calendar

on:
  workflow_dispatch:
  schedule:
    # This triggers the workflow every day at 4:00 UTC
    - cron:  '30 4 * * *'


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install poetry
        run: |
          export POETRY_HOME=/opt/poetry
          curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0
          export PATH="/opt/poetry/bin:$PATH"
          poetry --version

      - name: Install deps
        run: poetry install

      - name: Sync
        run: poetry run python3 main.py